version: '3.9'
services:
  mongo:
    image: mongo:latest
    container_name: securepass-mongo
    ports:
      - "27017:27017"
    volumes:
      - /Volumes/Crucial1TB/Docker/Volumes/mongo-data:/data/db
    restart: unless-stopped